language: node_js
node_js:
- 8
- 6
after_success:
- npm run build
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: UPAyaTKtIwerGqoZEgFh75kgLHfi0oxipg3LBSayzW8revwlbB0IMvP5x0akGGI4TJtoywdEec1GfU2Cex87j+i8mdSxR1jt1ZJICmtisyfQb30OXdQeV/jTmbecWq+1MHQJ2cKJnY67yC9i4/EKZe94bh/5Xxv1Tigcx80ngTFULfdIGliNHKOOPXrHoDw7mmE7WfplcnOrc8eioxbX0EJ6VkZ3KvLHnMzLn1lSe0sJ0w7ryQlvy2tkDMkfViKcB71OgOuRSEY5Wo+XOEn2+jg4lR1HMd7CEQU1yp2IpiPI4YVSFXjX+FO/wFsxNsbF7EkNKPZATvkD8FVglC5hkbZHcqAOWG0gE9bjO8EawacAEW3vckpsC467F5frXDc/SO+ByZRv/nxFAhTrOliZq2Uw2RMheaQ1/aRXI4n9H1OYSzngeoh1e14chYRJALu3pjgQN1tSPiAJ27C0BgwdrP09/MpG6TLEL+xaiTiDh6NLXkFprXclhV55ancTgbt/z4m+FIA0fqp3tRHjYvBcQgpTORzsPa1/JB3bVptZQ2l9YBX0Rx7FYlp+M4DuM1olxzmLKi8zMeVLMHIfqFZxXSDiK0gw95PKPNfTCvNeF1+cXEo9owYJyR+DX0Kpejbc43jd3bZ+eOu7xQfbyyDleps1brwwZXL/uGHpxInfX6k=
